name: Build Mod 1.8.9

on:
  push:
    branches: [ stable ]
  pull_request:
    branches: [ stable ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository and submodules
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup Java 8
        uses: actions/setup-java@v4
        with:
          distribution: "temurin" # Adopt đã đổi tên thành Temurin, dùng bản này ổn định hơn
          java-version: 8
          cache: "gradle"

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew setupCiWorkspace clean build
        
      - name: Upload Mod Jar Only
        uses: actions/upload-artifact@v4
        with:
          name: Chunky-1.8.9 # Đổi tên hiển thị trên GitHub cho dễ nhận biết
          # Lọc filter chỉ lấy file .jar chính thức, bỏ qua các file đính kèm như -sources hay -dev
          path: build/libs/*[!(-sources|-dev|-devkit)].jar
